version: "3"

services:
  message-broker:
    container_name: message-broker
    image: eclipse-mosquitto:latest
    volumes:
      - ${MGW_CORE_PATH}/message-broker-config:/mosquitto/config
      - message-broker-data:/mosquitto/data
      - message-broker-log:/mosquitto/log
    ports:
      - "1883:1883"
      - "8883:8883"
    restart: unless-stopped
    networks:
      - mgw-network

  device-management-service:
    container_name: device-management-service
    image: smartenergyplatform/device-manager:${MGW_ENVIRONMENT}
    ports:
      - "7002:80"
    environment:
      - DMCONF_MB_HOST=message-broker
      - DMCONF_MB_PORT=1883
      - DMCONF_LOGGER_LEVEL=debug
      - DMCONF_LOGGER_MQTT_LEVEL=info
      - DMCONF_CLIENT_NAME=device-management-service
      - DMCONF_CLIENT_CLEAN_SESSION=False
      - DMCONF_CLIENT_DEVICE_TOPIC=device/+
      - DMCONF_CLIENT_LW_TOPIC=device/+/lw
      - DMCONF_CLIENT_KEEP_ALIVE=10
      - DMCONF_CLIENT_RECONNECT=5
    depends_on:
      - message-broker
    restart: unless-stopped
    networks:
      - mgw-network

  senergy-connector-service:
    container_name: senergy-connector-service
    image: ghcr.io/senergy-platform/senergy-connector:latest
    volumes:
      - senergy-connector-service-data:/usr/src/app/cc-lib
    environment:
      - PCONF_MB_HOST=message-broker
      - PCONF_MB_PORT=1883
      - PCONF_DM_URL=http://device-management-service
      - PCONF_DM_API=devices
      - PCONF_LOGGER_LEVEL=debug
      - PCONF_LOGGER_MQTT_LEVEL=debug
      - PCONF_MQTTCLIENT_CLEAN_SESSION=false
      - PCONF_MQTTCLIENT_EVENT_TOPIC=event/#
      - PCONF_MQTTCLIENT_COMMAND_TOPIC=command
      - PCONF_MQTTCLIENT_RESPONSE_TOPIC=response/#
      - PCONF_MQTTCLIENT_KEEP_ALIVE=10
      - PCONF_DSROUTER_MAX_COMMAND_AGE=60
      - CONNECTORCONF_CONNECTOR=${SCS_CONNECTORCONF_CONNECTOR}
      - CONNECTORCONF_AUTH=${SCS_CONNECTORCONF_AUTH}
      - CONNECTORCONF_CREDENTIALS=${SCS_CONNECTORCONF_CREDENTIALS}
      - CONNECTORCONF_HUB=${SCS_CONNECTORCONF_HUB}
      - CONNECTORCONF_LOGGER=level:debug
      - CONNECTORCONF_API=${SCS_CONNECTORCONF_API}
      - MODULE_ID=senergy-connector
    depends_on:
      - message-broker
      - device-management-service
    restart: unless-stopped
    networks:
      - mgw-network

  gosund-connector:
    container_name: gosund-connector
    image: ghcr.io/senergy-platform/gosund-connector:latest
    environment:
      - TDCCONF_MB_HOST=message-broker
      - TDCCONF_MB_PORT=1883
      - TDCCONF_LOGGER_LEVEL=info
      - TDCCONF_LOGGER_MQTT_LEVEL=info
      - TDCCONF_CLIENT_CLEAN_SESSION=False
      - TDCCONF_CLIENT_DEVICE_TOPIC=device
      - TDCCONF_CLIENT_LW_TOPIC=lw
      - TDCCONF_CLIENT_EVENT_TOPIC=event
      - TDCCONF_CLIENT_COMMAND_TOPIC=command
      - TDCCONF_CLIENT_RESPONSE_TOPIC=response
      - TDCCONF_CLIENT_KEEP_ALIVE=10
      - TDCCONF_DEVICES_TYPE=${GC_DEVICES_TYPE}
      - TDCCONF_DEVICES_NAME=Gosund SP111
      - TDCCONF_DEVICES_LW_TOPIC=LWT
      - MODULE_ID=${GC_GOSUND_PREFIX}
    depends_on:
      - message-broker
      - device-management-service
    restart: unless-stopped
    networks:
      - mgw-network

  analytics-fog-master:
    container_name: analytics-fog-master
    image: ghcr.io/senergy-platform/analytics-fog-master:latest
    environment:
      - BROKER_ADDRESS=tcp://message-broker:1883
    volumes:
      - analytics-fog-master-data:/root/data
    depends_on:
      - message-broker
    restart: unless-stopped
    networks:
      - mgw-network

  analytics-fog-agent:
    container_name: analytics-fog-agent
    image: ghcr.io/senergy-platform/analytics-fog-agent:latest
    environment:
      - BROKER_HOST=message-broker
      - BROKER_PORT=1883
      - CONTAINER_BROKER_HOST=${MGW_HOST_IP}
#      - CONTAINER_NETWORK=${MGW_CORE_DIR_NAME}_mgw-network
      - CONTAINER_PULL_IMAGE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - analytics-fog-agent-data:/root/data
    depends_on:
      - message-broker
    restart: unless-stopped
    networks:
      - mgw-network

  z-way-connector:
    container_name: z-way-connector
    image: ghcr.io/senergy-platform/z-way-cc:${MGW_ENVIRONMENT}
    expose:
      - 8083
    ports:
      - 8083:8083
    volumes:
      - z-way-config:/opt/z-way-server/config
      - z-way-automation-storage:/opt/z-way-server/automation/storage
      - z-way-htdocs-smarthome-user:/opt/z-way-server/htdocs/smarthome/user
      - z-way-zddx:/opt/z-way-server/ZDDX
    devices:
      - '/dev/ttyAMA0:/dev/ttyAMA0'
    restart: unless-stopped
    depends_on:
      - message-broker
      - device-management-service
    networks:
      - mgw-network

volumes:
  device-type-storage-service-data: {}
  message-broker-data: {}
  message-broker-log: {}
  senergy-connector-service-data: {}
  analytics-fog-master-data: {}
  analytics-fog-agent-data: {}
  z-way-config: {}
  z-way-automation-storage: {}
  z-way-htdocs-smarthome-user: {}
  z-way-zddx: {}

networks:
  mgw-network:
    ipam:
      config:
        - subnet: ${MGW_DOCKER_SUBNET}
