version: "3"

services:
  eclipse-mosquitto:
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - ${MGW_CORE_PATH}/eclipse-mosquitto-config:/mosquitto/config
      - eclipse-mosquitto-data:/mosquitto/data
      - eclipse-mosquitto-log:/mosquitto/log
    ports:
      - "1883:1883"
      - "8883:8883"
    restart: unless-stopped
    networks:
      mgw-network:
        aliases:
          - message-broker

  mgw-device-manager:
    container_name: mgw-device-manager
    image: ghcr.io/senergy-platform/mgw-device-manager:${MGW_ENVIRONMENT}
    ports:
      - "7002:80"
    environment:
      - CONF_MB_HOST=message-broker
      - CONF_MB_PORT=1883
      - CONF_LOGGER_LEVEL=${DM_CONF_LOGGER_LEVEL}
    depends_on:
      - eclipse-mosquitto
    restart: unless-stopped
    networks:
      mgw-network:
        aliases:
          - device-manager

  analytics-fog-master:
    container_name: analytics-fog-master
    image: ghcr.io/senergy-platform/analytics-fog-master:latest
    environment:
      - BROKER_ADDRESS=tcp://message-broker:1883
    volumes:
      - analytics-fog-master-data:/root/data
    depends_on:
      - eclipse-mosquitto
    restart: unless-stopped
    networks:
      - mgw-network

  analytics-fog-agent:
    container_name: analytics-fog-agent
    image: ghcr.io/senergy-platform/analytics-fog-agent:latest
    environment:
      - BROKER_HOST=message-broker
      - BROKER_PORT=1883
      - CONTAINER_BROKER_HOST=${MGW_HOST_IP}
      - CONTAINER_NETWORK=${MGW_CORE_DIR_NAME}_mgw-network
      - CONTAINER_PULL_IMAGE=${AFA_CONTAINER_PULL_IMAGE}
    volumes:
      - ${MGW_DOCKER_SOCKET}:/var/run/docker.sock
      - analytics-fog-agent-data:/root/data
    depends_on:
      - eclipse-mosquitto
      - analytics-fog-master
    restart: unless-stopped
    networks:
      - mgw-network

  mgw-senergy-connector:
    container_name: mgw-senergy-connector
    image: ghcr.io/senergy-platform/mgw-senergy-connector:${MGW_ENVIRONMENT}
    volumes:
      - mgw-senergy-connector-data:/usr/src/app/.data
    environment:
      - CONF_MB_HOST=message-broker
      - CONF_MB_PORT=1883
      - CONF_DM_URL=http://device-manager
      - CONF_DM_API=devices
      - CONF_MQTTCLIENT_QOS=${SC_CONF_MQTTCLIENT_QOS}
      - CONF_LOGGER_LEVEL=${SC_CONF_LOGGER_LEVEL}
      - CONF_LOGGER_MQTT_LEVEL=${SC_CONF_LOGGER_MQTT_LEVEL}
      - CONF_DSROUTER_MAX_COMMAND_AGE=${SC_CONF_DSROUTER_MAX_COMMAND_AGE}
      - CONF_HUB_NAME=${SC_CONF_HUB_NAME}
      - OVERRIDE_HUB_ID=${SC_OVERRIDE_HUB_ID}
      - CC_LIB_CONNECTOR_HOST=${SC_CC_LIB_CONNECTOR_HOST}
      - CC_LIB_CONNECTOR_PORT=${SC_CC_LIB_CONNECTOR_PORT}
      - CC_LIB_CONNECTOR_TLS=${SC_CC_LIB_CONNECTOR_TLS}
      - CC_LIB_CONNECTOR_QOS=${SC_CC_LIB_CONNECTOR_QOS}
      - CC_LIB_CONNECTOR_CLEAN_SESSION=${SC_CC_LIB_CONNECTOR_CLEAN_SESSION}
      - CC_LIB_CONNECTOR_LOW_LEVEL_LOGGER=${SC_CC_LIB_CONNECTOR_LOW_LEVEL_LOGGER}
      - CC_LIB_API_HUB_ENDPT=${SC_CC_LIB_API_HUB_ENDPT}
      - CC_LIB_API_DEVICE_ENDPT=${SC_CC_LIB_API_DEVICE_ENDPT}
      - CC_LIB_API_AUTH_ENDPT=${SC_CC_LIB_API_AUTH_ENDPT}
      - CC_LIB_CREDENTIALS_USER=${SC_CC_LIB_CREDENTIALS_USER}
      - CC_LIB_CREDENTIALS_PW=${SC_CC_LIB_CREDENTIALS_PW}
      - CC_LIB_CREDENTIALS_CLIENT_ID=${SC_CC_LIB_CREDENTIALS_CLIENT_ID}
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  hue-bridge-dc:
    container_name: hue-bridge-dc
    image: ghcr.io/senergy-platform/hue-bridge-dc:${MGW_ENVIRONMENT}
    environment:
      - CONF_STARTDELAY_ENABLED=True
      - CONF_MSGBROKER_HOST=message-broker
      - CONF_MSGBROKER_PORT=1883
      - CONF_LOGGER_LEVEL=${HBDC_CONF_LOGGER_LEVEL}
      - CONF_BRIDGE_API_KEY=${HBDC_CONF_BRIDGE_API_KEY}
      - CONF_BRIDGE_ID=${HBDC_CONF_BRIDGE_ID}
      - CONF_DISCOVERY_DEVICE_ID_PREFIX=${HBDC_CONF_DISCOVERY_DEVICE_ID_PREFIX}
      - CONF_SENERGY_DT_EXTENDED_COLOR_LIGHT=${HBDC_CONF_SENERGY_DT_EXTENDED_COLOR_LIGHT}
      - CONF_SENERGY_DT_ON_OFF_PLUG_IN_UNIT=${HBDC_CONF_SENERGY_DT_ON_OFF_PLUG_IN_UNIT}
      - CONF_SENERGY_DT_COLOR_LIGHT=${HBDC_CONF_SENERGY_DT_COLOR_LIGHT}
    volumes:
      - ${MGW_CORE_PATH}/.host_ip:/opt/host_ip
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  blebox-dc:
    container_name: blebox-dc
    image: ghcr.io/senergy-platform/blebox-dc:${MGW_ENVIRONMENT}
    environment:
      - CONF_STARTDELAY_ENABLED=True
      - CONF_MSGBROKER_HOST=message-broker
      - CONF_MSGBROKER_PORT=1883
      - CONF_LOGGER_LEVEL=${BDC_CONF_LOGGER_LEVEL}
      - CONF_DISCOVERY_DEVICE_ID_PREFIX=${BDC_CONF_DISCOVERY_DEVICE_ID_PREFIX}
      - CONF_SENERGY_DT_AIR_SENSOR=${BDC_CONF_SENERGY_DT_AIR_SENSOR}
    volumes:
      - ${MGW_CORE_PATH}/.host_ip:/opt/host_ip
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  smart-meter-dc:
    container_name: smart-meter-dc
    image: ghcr.io/senergy-platform/smart-meter-dc:${MGW_ENVIRONMENT}
    environment:
      - CONF_STARTDELAY_ENABLED=True
      - CONF_MSGBROKER_HOST=message-broker
      - CONF_MSGBROKER_PORT=1883
      - CONF_LOGGER_LEVEL=${SMDC_CONF_LOGGER_LEVEL}
      - CONF_DISCOVERY_DEVICE_ID_PREFIX=${SMDC_CONF_DISCOVERY_DEVICE_ID_PREFIX}
      - CONF_DISCOVERY_PORT_FILTER=${SMDC_CONF_DISCOVERY_PORT_FILTER}
      - CONF_SENERGY_DT_LGZXZMF100AC=${SMDC_CONF_SENERGY_DT_LGZXZMF100AC}
    devices:
      - ${SMDC_DEVICES_PATH}:${SMDC_DEVICES_PATH}
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  dyson-dc:
    container_name: dyson-dc
    image: ghcr.io/senergy-platform/dyson-dc:${MGW_ENVIRONMENT}
    environment:
      - CONF_MSGBROKER_HOST=message-broker
      - CONF_MSGBROKER_PORT=1883
      - CONF_STARTDELAY_ENABLED=True
      - CONF_LOGGER_LEVEL=${DDC_CONF_LOGGER_LEVEL}
      - CONF_DISCOVERY_DEVICE_ID_PREFIX=${DDC_CONF_DISCOVERY_DEVICE_ID_PREFIX}
      - CONF_ACCOUNT_EMAIL=${DDC_CONF_ACCOUNT_EMAIL}
      - CONF_ACCOUNT_PW=${DDC_CONF_ACCOUNT_PW}
      - CONF_ACCOUNT_COUNTRY=${DDC_CONF_ACCOUNT_COUNTRY}
      - CONF_SENERGY_DT_PURE_COOL_LINK=${DDC_CONF_SENERGY_DT_PURE_COOL_LINK}
    volumes:
      - ${MGW_CORE_PATH}/.host_ip:/opt/host_ip
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  gosund-dc:
    container_name: gosund-dc
    image: ghcr.io/senergy-platform/gosund-dc:${MGW_ENVIRONMENT}
    environment:
      - CONF_MB_HOST=message-broker
      - CONF_MB_PORT=1883
      - CONF_LOGGER_LEVEL=${GC_CONF_LOGGER_LEVEL}
      - CONF_DEVICES_TYPE=${GC_CONF_DEVICES_TYPE}
      - CONF_DEVICES_LW_TOPIC=${GC_CONF_DEVICES_LW_TOPIC}
      - MODULE_ID=${GC_GOSUND_PREFIX}
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  zwave2mqtt:
    container_name: zwave2mqtt
    image: robertslando/zwave2mqtt:latest
    tty: true
    stop_signal: SIGINT
    ports:
      - "8091:8091"
    devices:
      - ${Z2M_DEVICES_PATH}:${Z2M_DEVICES_PATH}
    volumes:
      - zwave2mqtt_store:/usr/src/app/store
    depends_on:
      - eclipse-mosquitto
    restart: unless-stopped
    networks:
      - mgw-network

  mgw-zwave-dc:
    container_name: mgw-zwave-dc
    image: ghcr.io/senergy-platform/mgw-zwave-dc:${MGW_ENVIRONMENT}
    environment:
      - DEVICE_ID_PREFIX=${ZDC_DEVICE_ID_PREFIX}
      - DEBUG=${ZDC_DEBUG}
      - UPDATE_PERIOD=${ZDC_UPDATE_PERIOD}
      - DELETE_MISSING_DEVICES=${ZDC_DELETE_MISSING_DEVICES}
      - DELETE_HUSKS=${ZDC_DELETE_HUSKS}
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
      - zwave2mqtt
    restart: unless-stopped
    networks:
      - mgw-network

  camunda-db:
    image: postgres:11.2
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_PASSWORD=${CDB_POSTGRES_PASSWORD}
      - POSTGRES_USER=${CDB_POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - camunda-db-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - mgw-network

  camunda:
    image: ghcr.io/senergy-platform/process-engine:arm-${MGW_ENVIRONMENT}
    environment:
      - DB_USERNAME=${CDB_POSTGRES_USER}
      - DB_PASSWORD=${CDB_POSTGRES_PASSWORD}
      - DB_URL=jdbc:postgresql://camunda-db:5432/camunda
      - DB_PORT=5432
      - DB_NAME=camunda
      - DB_HOST=camunda-db
      - DB_DRIVER=org.postgresql.Driver
      - DATABASE=postgres
    restart: unless-stopped
    depends_on:
      - camunda-db
    networks:
      - mgw-network

  mgw-notify:
    image: ghcr.io/senergy-platform/mgw-notifier:${MGW_ENVIRONMENT}
    environment:
      - DEBUG=${NOTI_DEBUG}
      - NOTIFICATION_URL=${NOTI_NOTIFICATION_URL}
      - AUTH_ENDPOINT=${NOTI_AUTH_ENDPOINT}
      - AUTH_USER_NAME=${NOTI_AUTH_USER_NAME}
      - AUTH_PASSWORD=${NOTI_AUTH_PASSWORD}
    networks:
      - mgw-network

  mgw-process-sync-client:
    image: ghcr.io/senergy-platform/mgw-process-sync-client:${MGW_ENVIRONMENT}
    environment:
      - CAMUNDA_DB=postgres://${CDB_POSTGRES_USER}:${CDB_POSTGRES_PASSWORD}@camunda-db/camunda?sslmode=disable
      - CAMUNDA_URL=http://camunda:8080
      - MQTT_BROKER=tcp://message-broker:1883
      - DEPLOYMENT_METADATA_STORAGE=/root/db/bolt.db
      - NOTIFICATION_URL=http://mgw-notify:8080
    volumes:
      - process-sync-client-data:/root/db
    restart: unless-stopped
    depends_on:
      - camunda-db
      - camunda
      - mgw-senergy-connector
    networks:
      - mgw-network

  mgw-external-task-worker:
    image: ghcr.io/senergy-platform/mgw-external-task-worker:${MGW_ENVIRONMENT}
    environment:
      - COMPLETION_STRATEGY=${ETW_COMPLETION_STRATEGY}
      - CAMUNDA_TOPIC=${ETW_CAMUNDA_TOPIC}
      - AUTH_ENDPOINT=${ETW_AUTH_ENDPOINT}
      - AUTH_USER_NAME=${ETW_AUTH_USER_NAME}
      - AUTH_PASSWORD=${ETW_AUTH_PASSWORD}
      - CAMUNDA_URL=http://camunda:8080
      - MQTT_BROKER=tcp://message-broker:1883
      - DEVICE_REPO_URL=${ETW_DEVICE_REPO_URL}
      - DEBUG=${ETW_DEBUG}
    restart: unless-stopped
    depends_on:
      - camunda-db
      - camunda
      - mgw-senergy-connector
    networks:
      - mgw-network

volumes:
  eclipse-mosquitto-data:
  eclipse-mosquitto-log:
  mgw-senergy-connector-data:
  analytics-fog-master-data:
  analytics-fog-agent-data:
  zwave2mqtt_store:
  camunda-db-data:
  process-sync-client-data:

networks:
  mgw-network:
    ipam:
      config:
        - subnet: ${MGW_DOCKER_SUBNET}
