version: "3"

services:
  eclipse-mosquitto:
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - ${MGW_CORE_PATH}/eclipse-mosquitto-config:/mosquitto/config
      - eclipse-mosquitto-data:/mosquitto/data
      - eclipse-mosquitto-log:/mosquitto/log
    ports:
      - "1883:1883"
      - "8883:8883"
    restart: unless-stopped
    privileged: true
    networks:
      mgw-network:
        aliases:
          - message-broker

  mgw-device-manager:
    container_name: mgw-device-manager
    image: ghcr.io/senergy-platform/mgw-device-manager:${MGW_ENVIRONMENT}
    ports:
      - "7002:80"
    environment:
      - CONF_MB_HOST=message-broker
      - CONF_MB_PORT=1883
      - CONF_LOGGER_LEVEL=${DM_CONF_LOGGER_LEVEL}
    depends_on:
      - eclipse-mosquitto
    restart: unless-stopped
    networks:
      mgw-network:
        aliases:
          - device-manager

  analytics-fog-master:
    container_name: analytics-fog-master
    image: ghcr.io/senergy-platform/analytics-fog-master:latest
    environment:
      - BROKER_ADDRESS=tcp://message-broker:1883
    volumes:
      - analytics-fog-master-data:/root/data
    depends_on:
      - eclipse-mosquitto
    restart: unless-stopped
    networks:
      - mgw-network

  analytics-fog-agent:
    container_name: analytics-fog-agent
    image: ghcr.io/senergy-platform/analytics-fog-agent:latest
    environment:
      - BROKER_HOST=message-broker
      - BROKER_PORT=1883
      - CONTAINER_BROKER_HOST=${MGW_HOST_IP}
      - CONTAINER_NETWORK=${MGW_CORE_DIR_NAME}_mgw-network
      - CONTAINER_PULL_IMAGE=${AFA_CONTAINER_PULL_IMAGE}
    volumes:
      - ${MGW_DOCKER_SOCKET}:/var/run/docker.sock
      - analytics-fog-agent-data:/root/data
    depends_on:
      - eclipse-mosquitto
      - analytics-fog-master
    restart: unless-stopped
    networks:
      - mgw-network

  mgw-senergy-connector:
    container_name: mgw-senergy-connector
    image: ghcr.io/senergy-platform/mgw-senergy-connector:${MGW_ENVIRONMENT}
    volumes:
      - mgw-senergy-connector-data:/usr/src/app/.data
    environment:
      - CONF_MB_HOST=message-broker
      - CONF_MB_PORT=1883
      - CONF_DM_URL=http://device-manager
      - CONF_DM_API=devices
      - CONF_MQTTCLIENT_QOS=${SC_CONF_MQTTCLIENT_QOS}
      - CONF_LOGGER_LEVEL=${SC_CONF_LOGGER_LEVEL}
      - CONF_LOGGER_MQTT_LEVEL=${SC_CONF_LOGGER_MQTT_LEVEL}
      - CONF_DSROUTER_MAX_COMMAND_AGE=${SC_CONF_DSROUTER_MAX_COMMAND_AGE}
      - CONF_HUB_NAME=${SC_CONF_HUB_NAME}
      - OVERRIDE_HUB_ID=${SC_OVERRIDE_HUB_ID}
      - CC_LIB_CONNECTOR_HOST=${SC_CC_LIB_CONNECTOR_HOST}
      - CC_LIB_CONNECTOR_PORT=${SC_CC_LIB_CONNECTOR_PORT}
      - CC_LIB_CONNECTOR_TLS=${SC_CC_LIB_CONNECTOR_TLS}
      - CC_LIB_CONNECTOR_QOS=${SC_CC_LIB_CONNECTOR_QOS}
      - CC_LIB_CONNECTOR_CLEAN_SESSION=${SC_CC_LIB_CONNECTOR_CLEAN_SESSION}
      - CC_LIB_CONNECTOR_LOW_LEVEL_LOGGER=${SC_CC_LIB_CONNECTOR_LOW_LEVEL_LOGGER}
      - CC_LIB_API_HUB_ENDPT=${SC_CC_LIB_API_HUB_ENDPT}
      - CC_LIB_API_DEVICE_ENDPT=${SC_CC_LIB_API_DEVICE_ENDPT}
      - CC_LIB_API_AUTH_ENDPT=${SC_CC_LIB_API_AUTH_ENDPT}
      - CC_LIB_CREDENTIALS_USER=${SC_CC_LIB_CREDENTIALS_USER}
      - CC_LIB_CREDENTIALS_PW=${SC_CC_LIB_CREDENTIALS_PW}
      - CC_LIB_CREDENTIALS_CLIENT_ID=${SC_CC_LIB_CREDENTIALS_CLIENT_ID}
      - CC_LIB_DEVICE_ATTRIBUTE_ORIGIN=${SC_CC_LIB_DEVICE_ATTRIBUTE_ORIGIN}
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  hue-bridge-dc:
    container_name: hue-bridge-dc
    image: ghcr.io/senergy-platform/hue-bridge-dc:${MGW_ENVIRONMENT}
    environment:
      - CONF_STARTDELAY_ENABLED=True
      - CONF_MSGBROKER_HOST=message-broker
      - CONF_MSGBROKER_PORT=1883
      - CONF_LOGGER_LEVEL=${HBDC_CONF_LOGGER_LEVEL}
      - CONF_BRIDGE_API_KEY=${HBDC_CONF_BRIDGE_API_KEY}
      - CONF_BRIDGE_ID=${HBDC_CONF_BRIDGE_ID}
      - CONF_DISCOVERY_DEVICE_ID_PREFIX=${HBDC_CONF_DISCOVERY_DEVICE_ID_PREFIX}
      - CONF_SENERGY_DT_EXTENDED_COLOR_LIGHT=${HBDC_CONF_SENERGY_DT_EXTENDED_COLOR_LIGHT}
      - CONF_SENERGY_DT_ON_OFF_PLUG_IN_UNIT=${HBDC_CONF_SENERGY_DT_ON_OFF_PLUG_IN_UNIT}
      - CONF_SENERGY_DT_COLOR_LIGHT=${HBDC_CONF_SENERGY_DT_COLOR_LIGHT}
      - CONF_SENERGY_DT_COLOR_TEMPERATURE_LIGHT=${HBDC_CONF_SENERGY_DT_COLOR_TEMPERATURE_LIGHT}
      - CONF_SENERGY_DT_DIMMABLE_LIGHT=${HBDC_CONF_SENERGY_DT_DIMMABLE_LIGHT}
      - CONF_SENERGY_DT_ZLL_PRESENCE=${HBDC_CONF_SENERGY_DT_ZLL_PRESENCE}
      - CONF_SENERGY_DT_ZLL_SWITCH=${HBDC_CONF_SENERGY_DT_ZLL_SWITCH}
    volumes:
      - ${MGW_CORE_PATH}/.host_ip:/opt/host_ip
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  blebox-dc:
    container_name: blebox-dc
    image: ghcr.io/senergy-platform/blebox-dc:${MGW_ENVIRONMENT}
    environment:
      - CONF_STARTDELAY_ENABLED=True
      - CONF_MSGBROKER_HOST=message-broker
      - CONF_MSGBROKER_PORT=1883
      - CONF_LOGGER_LEVEL=${BDC_CONF_LOGGER_LEVEL}
      - CONF_DISCOVERY_DEVICE_ID_PREFIX=${BDC_CONF_DISCOVERY_DEVICE_ID_PREFIX}
      - CONF_SENERGY_DT_AIR_SENSOR=${BDC_CONF_SENERGY_DT_AIR_SENSOR}
    volumes:
      - ${MGW_CORE_PATH}/.host_ip:/opt/host_ip
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  smart-meter-dc:
    container_name: smart-meter-dc
    image: ghcr.io/senergy-platform/smart-meter-dc:${MGW_ENVIRONMENT}
    environment:
      - CONF_STARTDELAY_ENABLED=True
      - CONF_MSGBROKER_HOST=message-broker
      - CONF_MSGBROKER_PORT=1883
      - CONF_LOGGER_LEVEL=${SMDC_CONF_LOGGER_LEVEL}
      - CONF_DISCOVERY_DEVICE_ID_PREFIX=${SMDC_CONF_DISCOVERY_DEVICE_ID_PREFIX}
      - CONF_DISCOVERY_PORT_FILTER=${SMDC_CONF_DISCOVERY_PORT_FILTER}
      - CONF_SENERGY_DT_LGZXZMF100AC=${SMDC_CONF_SENERGY_DT_LGZXZMF100AC}
    devices:
      - ${SMDC_DEVICES_PATH}:${SMDC_DEVICES_PATH}
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  dyson-dc:
    container_name: dyson-dc
    image: ghcr.io/senergy-platform/dyson-dc:${MGW_ENVIRONMENT}
    environment:
      - CONF_MSGBROKER_HOST=message-broker
      - CONF_MSGBROKER_PORT=1883
      - CONF_STARTDELAY_ENABLED=True
      - CONF_LOGGER_LEVEL=${DDC_CONF_LOGGER_LEVEL}
      - CONF_DISCOVERY_DEVICE_ID_PREFIX=${DDC_CONF_DISCOVERY_DEVICE_ID_PREFIX}
      - CONF_ACCOUNT_EMAIL=${DDC_CONF_ACCOUNT_EMAIL}
      - CONF_ACCOUNT_PW=${DDC_CONF_ACCOUNT_PW}
      - CONF_ACCOUNT_COUNTRY=${DDC_CONF_ACCOUNT_COUNTRY}
      - CONF_SENERGY_DT_PURE_COOL_LINK=${DDC_CONF_SENERGY_DT_PURE_COOL_LINK}
    volumes:
      - ${MGW_CORE_PATH}/.host_ip:/opt/host_ip
      - dyson-dc-data:/opt/storage
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  zwave2mqtt:
    container_name: zwave2mqtt
    image: ${Z2M_IMAGE}
    tty: true
    stop_signal: SIGINT
    ports:
      - "8091:8091"
    devices:
      - ${Z2M_DEVICES_PATH}:${Z2M_DEVICES_PATH}
    volumes:
      - zwave2mqtt_store:/usr/src/app/store
    depends_on:
      - eclipse-mosquitto
    restart: unless-stopped
    networks:
      - mgw-network

  mgw-zwave-dc:
    container_name: mgw-zwave-dc
    image: ghcr.io/senergy-platform/mgw-zwave-dc:${MGW_ENVIRONMENT}
    environment:
      - DEVICE_ID_PREFIX=${ZDC_DEVICE_ID_PREFIX}
      - DEBUG=${ZDC_DEBUG}
      - UPDATE_PERIOD=${ZDC_UPDATE_PERIOD}
      - DELETE_MISSING_DEVICES=${ZDC_DELETE_MISSING_DEVICES}
      - DELETE_HUSKS=${ZDC_DELETE_HUSKS}
      - ZWAVE_MQTT_BROKER=${ZDC_ZWAVE_MQTT_BROKER}
      - ZWAVE_MQTT_USER=${ZDC_ZWAVE_MQTT_USER}
      - ZWAVE_MQTT_PW=${ZDC_ZWAVE_MQTT_PW}
      - ZWAVE_MQTT_CLIENT_ID=${ZDC_ZWAVE_MQTT_CLIENT_ID}
      - ZWAVE_VALUE_EVENT_TOPIC=${ZDC_ZWAVE_VALUE_EVENT_TOPIC}
      - ZWAVE_MQTT_API_TOPIC=${ZDC_ZWAVE_MQTT_API_TOPIC}
      - ZWAVE_NETWORK_EVENTS_TOPIC=${ZDC_ZWAVE_NETWORK_EVENTS_TOPIC}
      - ZWAVE_MQTT_DEVICE_STATE_TOPIC=${ZDC_ZWAVE_VALUE_EVENT_TOPIC}
      - ZWAVE_CONTROLLER=${ZDC_ZWAVE_CONTROLLER}
      - MGW_MQTT_BROKER=${ZDC_MGW_MQTT_BROKER}
      - MGW_MQTT_PW=${ZDC_MGW_MQTT_PW}
      - MGW_MQTT_CLIENT_ID=${ZDC_MGW_MQTT_CLIENT_ID}
      - EVENTS_FOR_UNREGISTERED_DEVICES=${ZDC_EVENTS_FOR_UNREGISTERED_DEVICES}
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  camunda-db:
    image: postgres:11.2
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_PASSWORD=${CDB_POSTGRES_PASSWORD}
      - POSTGRES_USER=${CDB_POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - camunda-db-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - mgw-network

  camunda:
    image: ghcr.io/senergy-platform/process-engine:arm-${MGW_ENVIRONMENT}
    environment:
      - DB_USERNAME=${CDB_POSTGRES_USER}
      - DB_PASSWORD=${CDB_POSTGRES_PASSWORD}
      - DB_URL=jdbc:postgresql://camunda-db:5432/camunda
      - DB_PORT=5432
      - DB_NAME=camunda
      - DB_HOST=camunda-db
      - DB_DRIVER=org.postgresql.Driver
      - DATABASE=postgres
    restart: unless-stopped
    depends_on:
      - camunda-db
    networks:
      - mgw-network

  mgw-notify:
    image: ghcr.io/senergy-platform/mgw-notifier:${MGW_ENVIRONMENT}
    environment:
      - DEBUG=${NOTI_DEBUG}
      - NOTIFICATION_URL=${NOTI_NOTIFICATION_URL}
      - AUTH_ENDPOINT=${NOTI_AUTH_ENDPOINT}
      - AUTH_USER_NAME=${NOTI_AUTH_USER_NAME}
      - AUTH_PASSWORD=${NOTI_AUTH_PASSWORD}
    networks:
      - mgw-network

  mgw-process-sync-client:
    image: ghcr.io/senergy-platform/mgw-process-sync-client:${MGW_ENVIRONMENT}
    environment:
      - CAMUNDA_DB=postgres://${CDB_POSTGRES_USER}:${CDB_POSTGRES_PASSWORD}@camunda-db/camunda?sslmode=disable
      - CAMUNDA_URL=http://camunda:8080
      - MQTT_BROKER=tcp://message-broker:1883
      - DEPLOYMENT_METADATA_STORAGE=/root/db/bolt.db
      - NOTIFICATION_URL=http://mgw-notify:8080
    volumes:
      - process-sync-client-data:/root/db
    restart: unless-stopped
    depends_on:
      - camunda-db
      - camunda
      - mgw-senergy-connector
    networks:
      - mgw-network

  mgw-external-task-worker:
    image: ghcr.io/senergy-platform/mgw-external-task-worker:${MGW_ENVIRONMENT}
    environment:
      - COMPLETION_STRATEGY=${ETW_COMPLETION_STRATEGY}
      - CAMUNDA_TOPIC=${ETW_CAMUNDA_TOPIC}
      - AUTH_ENDPOINT=${ETW_AUTH_ENDPOINT}
      - AUTH_USER_NAME=${ETW_AUTH_USER_NAME}
      - AUTH_PASSWORD=${ETW_AUTH_PASSWORD}
      - CAMUNDA_URL=http://camunda:8080
      - MQTT_BROKER=tcp://message-broker:1883
      - DEVICE_REPO_URL=${ETW_DEVICE_REPO_URL}
      - DEBUG=${ETW_DEBUG}
      - PERMISSIONS_URL=${ETW_PERMISSIONS_SEARCH_URL}
    restart: unless-stopped
    depends_on:
      - camunda-db
      - camunda
      - mgw-senergy-connector
    networks:
      - mgw-network

  mgw-switchbotbluetooth-dc:
    container_name: mgw-switchbotbluetooth-dc
    image: ghcr.io/senergy-platform/mgw-switchbotbluetooth-dc:${MGW_ENVIRONMENT}
    environment:
      - CONF_LOGGER_LEVEL=${SBB_CONF_LOGGER_LEVEL}
      - CONF_DISCOVERY_SCAN_DELAY=${SBB_CONF_DISCOVERY_SCAN_DELAY}
      - CONF_DISCOVERY_DEVICE_ID_PREFIX=${SBB_CONF_DISCOVERY_DEVICE_ID_PREFIX}
      - CONF_DISCOVERY_COMMAND_RETRIES=${SBB_CONF_DISCOVERY_COMMAND_RETRIES}
      - CONF_DISCOVERY_ADAPTER=${SBB_CONF_DISCOVERY_ADAPTER}
      - CONF_CLIENT_KEEPALIVE=${SBB_CONF_CLIENT_KEEPALIVE}
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
      - zwave2mqtt
    restart: unless-stopped
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    networks:
      - mgw-network

  mgw-kasa-dc:
    container_name: mgw-kasa-dc
    image: ghcr.io/senergy-platform/mgw-kasa-dc:${MGW_ENVIRONMENT}
    environment:
      - CONF_LOGGER_LEVEL=${KASA_CONF_LOGGER_LEVEL}
      - CONF_DISCOVERY_SCAN_DELAY=${KASA_CONF_DISCOVERY_SCAN_DELAY}
      - CONF_DISCOVERY_DEVICE_ID_PREFIX=${KASA_CONF_DISCOVERY_DEVICE_ID_PREFIX}
      - CONF_DISCOVERY_TIMEOUT=${KASA_CONF_DISCOVERY_TIMEOUT}
      - CONF_DISCOVERY_SUBNET=${KASA_CONF_DISCOVERY_SUBNET}
      - CONF_DISCOVERY_IP_LIST=${KASA_CONF_DISCOVERY_IP_LIST}
      - CONF_DISCOVERY_NUM_WORKERS=${KASA_CONF_DISCOVERY_NUM_WORKERS}
      - CONF_CLIENT_KEEPALIVE=${KASA_CONF_CLIENT_KEEPALIVE}
      - CONF_SENERGY_EVENTS_STATUS_SECONDS=${KASA_CONF_SENERGY_EVENTS_STATUS_SECONDS}
      - CONF_SENERGY_EVENTS_ENERGY_SECONDS=${KASA_CONF_SENERGY_EVENTS_ENERGY_SECONDS}
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  mgw-mqtt-dc:
    container_name: mgw-mqtt-dc
    image: ghcr.io/senergy-platform/mgw-mqtt-dc:${MGW_ENVIRONMENT}
    environment:
      - MGW_MQTT_BROKER=tcp://message-broker:1883
      - MGW_MQTT_CLIENT_ID=mgw-mqtt-dc
      - MQTT_BROKER=${MQTT_DC_CONF_MQTT_BROKER}
      - MQTT_USER=${MQTT_DC_CONF_MQTT_USER}
      - MQTT_PW=${MQTT_DC_CONF_MQTT_PW}
      - MQTT_CMD_CLIENT_ID=${MQTT_DC_CONF_MQTT_CMD_CLIENT_ID}
      - MQTT_EVENT_CLIENT_ID=${MQTT_DC_CONF_MQTT_EVENT_CLIENT_ID}
      - GENERATOR_USE=${MQTT_DC_CONF_GENERATOR_USE}
      - GENERATOR_AUTH_USERNAME=${SC_CC_LIB_CREDENTIALS_USER}
      - GENERATOR_AUTH_PASSWORD=${SC_CC_LIB_CREDENTIALS_PW}
      - GENERATOR_AUTH_ENDPOINT=${MQTT_DC_CONF_GENERATOR_AUTH_ENDPOINT}
      - GENERATOR_PERMISSION_SEARCH_URL=${MQTT_DC_CONF_GENERATOR_PERMISSION_SEARCH_URL}
      - GENERATOR_DEVICE_REPOSITORY_URL=${MQTT_DC_CONF_GENERATOR_DEVICE_REPOSITORY_URL}
      - GENERATOR_TRUNCATE_DEVICE_PREFIX=${MQTT_DC_CONF_GENERATOR_TRUNCATE_DEVICE_PREFIX}
      - UPDATE_PERIOD=${MQTT_DC_CONF_UPDATE_PERIOD}
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  mgw-senec-dc:
    container_name: mgw-senec-dc
    image: ghcr.io/senergy-platform/mgw-senec-dc:${MGW_ENVIRONMENT}
    environment:
      - CONF_LOGGER_LEVEL=${SENEC_CONF_LOGGER_LEVEL}
      - CONF_DISCOVERY_SCAN_DELAY=${SENEC_CONF_DISCOVERY_SCAN_DELAY}
      - CONF_DISCOVERY_DEVICE_ID_PREFIX=${SENEC_CONF_DISCOVERY_DEVICE_ID_PREFIX}
      - CONF_DISCOVERY_TIMEOUT=${SENEC_CONF_DISCOVERY_TIMEOUT}
      - CONF_DISCOVERY_SUBNET=${SENEC_CONF_DISCOVERY_SUBNET}
      - CONF_DISCOVERY_IP_LIST=${SENEC_CONF_DISCOVERY_IP_LIST}
      - CONF_DISCOVERY_NUM_WORKERS=${SENEC_CONF_DISCOVERY_NUM_WORKERS}
      - CONF_CLIENT_KEEPALIVE=${SENEC_CONF_CLIENT_KEEPALIVE}
      - CONF_SENERGY_EVENTS_ENERGY_SECONDS=${SENEC_CONF_SENERGY_EVENTS_ENERGY_SECONDS}
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    networks:
      - mgw-network

  mgw-madoka-dc:
    container_name: mgw-madoka-dc
    image: ghcr.io/senergy-platform/mgw-madoka-dc:${MGW_ENVIRONMENT}
    environment:
      - MQTT_HOST=message-broker
      - MQTT_PORT=1883
      - MQTT_USER=
      - MQTT_PW=
      - MQTT_SSL=False
      - MQTT_PREFIX=madoka
      - MQTT_INTERVAL=${MADOKA_INTERVAL}
      - MADOKA_MAC=${MADOKA_MAC}
      - BT_ADAPTER=${MADOKA_BT_ADAPTER}
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    networks:
      - mgw-network

  mgw-tesla-dc:
    container_name: mgw-tesla-dc
    image: ghcr.io/senergy-platform/mgw-tesla-dc:${MGW_ENVIRONMENT}
    environment:
      - CONF_MSGBROKER_HOST=message-broker
      - CONF_MSGBROKER_PORT=1883
      - CONF_LOGGER_LEVEL=${TESLA_CONF_LOGGER_LEVEL}
      - CONF_DISCOVERY_SCAN_DELAY=${TESLA_CONF_DISCOVERY_SCAN_DELAY}
      - CONF_SENERGY_EVENTS_GET_VEHICLE_DATA_SECONDS=${TESLA_CONF_SENERGY_EVENTS_GET_VEHICLE_DATA_SECONDS}
      - CONF_TESLA_EMAIL=${TESLA_CONF_TESLA_EMAIL}
      - CONF_TESLA_RESFRESHTOKEN=${TESLA_CONF_TESLA_RESFRESHTOKEN}
    depends_on:
      - eclipse-mosquitto
      - mgw-device-manager
    restart: unless-stopped
    volumes:
      - mgw-tesla-dc-data:/usr/src/app/.cache
    networks:
      - mgw-network

volumes:
  eclipse-mosquitto-data:
  eclipse-mosquitto-log:
  mgw-senergy-connector-data:
  analytics-fog-master-data:
  analytics-fog-agent-data:
  zwave2mqtt_store:
  camunda-db-data:
  process-sync-client-data:
  dyson-dc-data:
  mgw-tesla-dc-data:

networks:
  mgw-network:
    ipam:
      config:
        - subnet: ${MGW_DOCKER_SUBNET}
